// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Challenge struct {
	ID          int64     `json:"id"`
	StartDate   time.Time `json:"start_date"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Competition struct {
	ID           int64     `json:"id"`
	ChallengerID int64     `json:"challenger_id"`
	RivalID      int64     `json:"rival_id"`
	ChallengeID  int64     `json:"challenge_id"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type CompetitionTodo struct {
	ID            int64     `json:"id"`
	CompetitionID int64     `json:"competition_id"`
	TodoID        int64     `json:"todo_id"`
	IsCompleted   bool      `json:"is_completed"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Todo struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	ChallengeID int64     `json:"challenge_id"`
	Period      string    `json:"period"`
	Point       float64   `json:"point"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Score     float64   `json:"score"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
