// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChallenge(ctx context.Context, id int64) (Challenge, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
