// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateCompetition(ctx context.Context, arg CreateCompetitionParams) (Competition, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChallenge(ctx context.Context, id int64) (Challenge, error)
	GetCompetition(ctx context.Context, id int64) (Competition, error)
	GetCompetitionsByChallenge(ctx context.Context, challengeID int64) ([]Competition, error)
	GetCompetitionsByUser(ctx context.Context, challengerID int64) ([]Competition, error)
	GetCompetitionsByUserAndChallenge(ctx context.Context, arg GetCompetitionsByUserAndChallengeParams) (Competition, error)
	GetTodo(ctx context.Context, id int64) (Todo, error)
	GetTodosByChallenge(ctx context.Context, challengeID int64) ([]Todo, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
